version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN: 
    secure: s1pzntlxq2NgafLLGu2cJHVtDFEgkI33a
before_build:
- ps: nuget restore ./Bg-Fishing/Bg-Fishing.sln
build:
  project: Bg-Fishing/Bg-Fishing.sln
  verbosity: minimal
after_test:
- .\Bg-Fishing\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover TestResult.xml