// <auto-generated />
namespace Bg_Fishing.Auth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "201703231110094_User_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
